name: testando_terraform
run-name: ${{ github.workflow }}-${{ github.run_id }}-${{ github.actor }}
on:
  push:
jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tfsec
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Run tfsec
        run: tfsec .

        